
//input ports
add mapped point AC_STRESS_CLK AC_STRESS_CLK
add mapped point RESETB RESETB
add mapped point LOAD LOAD
add mapped point SEL_INV SEL_INV
add mapped point SEL_NAND SEL_NAND
add mapped point SEL_NOR SEL_NOR
add mapped point START START
add mapped point AC_DC AC_DC
add mapped point MEAS_TRIG MEAS_TRIG
add mapped point VDD VDD
add mapped point VSS VSS

//output ports
add mapped point BF_COUNT[11] BF_COUNT[11]
add mapped point BF_COUNT[10] BF_COUNT[10]
add mapped point BF_COUNT[9] BF_COUNT[9]
add mapped point BF_COUNT[8] BF_COUNT[8]
add mapped point BF_COUNT[7] BF_COUNT[7]
add mapped point BF_COUNT[6] BF_COUNT[6]
add mapped point BF_COUNT[5] BF_COUNT[5]
add mapped point BF_COUNT[4] BF_COUNT[4]
add mapped point BF_COUNT[3] BF_COUNT[3]
add mapped point BF_COUNT[2] BF_COUNT[2]
add mapped point BF_COUNT[1] BF_COUNT[1]
add mapped point BF_COUNT[0] BF_COUNT[0]

//inout ports




//Sequential Pins
add mapped point odometer_top/odometer_meas_detect_inst/edge_detector_inst/shift_reg/DATA_OUT[2]/q odometer_top_odometer_meas_detect_inst/edge_detector_inst_shift_reg_DATA_OUT_reg[2]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/edge_detector_inst/shift_reg/DATA_OUT[1]/q odometer_top_odometer_meas_detect_inst/edge_detector_inst_shift_reg_DATA_OUT_reg[1]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/edge_detector_inst/shift_reg/DATA_OUT[0]/q odometer_top_odometer_meas_detect_inst/edge_detector_inst_shift_reg_DATA_OUT_reg[0]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[11]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[11]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[11]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[11]/QN 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[10]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[10]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[10]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[10]/QN 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[9]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[9]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[9]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[9]/QN 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[8]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[8]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[8]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[8]/QN 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[7]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[7]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[7]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[7]/QN 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[6]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[6]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[6]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[6]/QN 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[5]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[5]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[5]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[5]/QN 
add mapped point odometer_top/odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER[7]/q odometer_top_odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER_reg[7]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER[7]/q odometer_top_odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER_reg[7]/QN 
add mapped point odometer_top/odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER[6]/q odometer_top_odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER_reg[6]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[4]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[4]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[4]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[4]/QN 
add mapped point odometer_top/odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER[11]/q odometer_top_odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER_reg[11]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER[11]/q odometer_top_odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER_reg[11]/QN 
add mapped point odometer_top/odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER[5]/q odometer_top_odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER_reg[5]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER[9]/q odometer_top_odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER_reg[9]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER[9]/q odometer_top_odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER_reg[9]/QN 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[3]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[3]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[3]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[3]/QN 
add mapped point odometer_top/odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER[10]/q odometer_top_odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER_reg[10]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER[10]/q odometer_top_odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER_reg[10]/QN 
add mapped point odometer_top/odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER[8]/q odometer_top_odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER_reg[8]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER[8]/q odometer_top_odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER_reg[8]/QN 
add mapped point odometer_top/odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER[3]/q odometer_top_odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER_reg[3]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER[3]/q odometer_top_odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER_reg[3]/QN 
add mapped point odometer_top/odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER[12]/q odometer_top_odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER_reg[12]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER[4]/q odometer_top_odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER_reg[4]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[2]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[2]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[2]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[2]/QN 
add mapped point odometer_top/odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER[2]/q odometer_top_odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER_reg[2]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[1]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[1]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[1]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[1]/QN 
add mapped point odometer_top/odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER[1]/q odometer_top_odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER_reg[1]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/MEAS_DONE/q odometer_top_odometer_meas_detect_inst/MEAS_DONE_reg/Q 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[0]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[0]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/BF_COUNTER[0]/q odometer_top_odometer_meas_detect_inst/BF_COUNTER_reg[0]/QN 
add mapped point odometer_top/odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER[0]/q odometer_top_odometer_meas_detect_inst/DEADZONE_ESCAPE_COUNTER_reg[0]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/DETECT_COUNTER[1]/q odometer_top_odometer_meas_detect_inst/DETECT_COUNTER_reg[1]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/DETECT_COUNTER[1]/q odometer_top_odometer_meas_detect_inst/DETECT_COUNTER_reg[1]/QN 
add mapped point odometer_top/odometer_meas_detect_inst/DETECT_COUNTER[0]/q odometer_top_odometer_meas_detect_inst/DETECT_COUNTER_reg[0]/Q 
add mapped point odometer_top/odometer_meas_detect_inst/DETECT_COUNTER[0]/q odometer_top_odometer_meas_detect_inst/DETECT_COUNTER_reg[0]/QN 
add mapped point odometer_top/EN_ROSC_shifted[0]/q odometer_top_EN_ROSC_shifted_reg[0]/Q 
add mapped point odometer_top/signal_ctrl_inst/CTRL[0]/q odometer_top_signal_ctrl_inst_CTRL_reg[0]/Q 
add mapped point odometer_top/signal_ctrl_inst/CTRL[4]/q odometer_top_signal_ctrl_inst_CTRL_reg[4]/Q 
add mapped point odometer_top/signal_ctrl_inst/CTRL[1]/q odometer_top_signal_ctrl_inst_CTRL_reg[1]/Q 
add mapped point odometer_top/signal_ctrl_inst/CTRL[3]/q odometer_top_signal_ctrl_inst_CTRL_reg[3]/Q 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[0]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[0]/Q 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[0]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[0]/QN 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[1]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[1]/Q 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[1]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[1]/QN 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[2]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[2]/Q 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[2]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[2]/QN 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[3]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[3]/Q 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[3]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[3]/QN 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[4]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[4]/Q 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[4]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[4]/QN 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[5]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[5]/Q 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[5]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[5]/QN 
add mapped point odometer_top/MEAS_STRESS/q odometer_top_MEAS_STRESS_reg/Q 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[7]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[7]/Q 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[7]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[7]/QN 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[8]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[8]/Q 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[8]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[8]/QN 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[9]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[9]/Q 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[9]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[9]/QN 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[10]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[10]/Q 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[10]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[10]/QN 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[11]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[11]/Q 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[11]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[11]/QN 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[6]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[6]/Q 
add mapped point odometer_top/parallel_latch_inst/PARALLEL_OUT[6]/q odometer_top_parallel_latch_inst_PARALLEL_OUT_reg[6]/QN 
add mapped point odometer_top/EN_ROSC_shifted[1]/q odometer_top_EN_ROSC_shifted_reg[1]/Q 
add mapped point odometer_top/signal_ctrl_inst/CTRL[2]/q odometer_top_signal_ctrl_inst_CTRL_reg[2]/Q 
add mapped point odometer_top/PC_OUT/q odometer_top_PC_OUT_reg/Q 



//Black Boxes



//Empty Modules as Blackboxes
add mapped point rosc_ref/ROSC_INV rosc_ref_ROSC_INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[0].INV rosc_ref_ROSC_INV/genblk1.inv[0].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[1].INV rosc_ref_ROSC_INV/genblk1.inv[1].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[2].INV rosc_ref_ROSC_INV/genblk1.inv[2].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[3].INV rosc_ref_ROSC_INV/genblk1.inv[3].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[4].INV rosc_ref_ROSC_INV/genblk1.inv[4].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[5].INV rosc_ref_ROSC_INV/genblk1.inv[5].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[6].INV rosc_ref_ROSC_INV/genblk1.inv[6].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[7].INV rosc_ref_ROSC_INV/genblk1.inv[7].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[8].INV rosc_ref_ROSC_INV/genblk1.inv[8].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[9].INV rosc_ref_ROSC_INV/genblk1.inv[9].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[10].INV rosc_ref_ROSC_INV/genblk1.inv[10].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[11].INV rosc_ref_ROSC_INV/genblk1.inv[11].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[12].INV rosc_ref_ROSC_INV/genblk1.inv[12].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[13].INV rosc_ref_ROSC_INV/genblk1.inv[13].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[14].INV rosc_ref_ROSC_INV/genblk1.inv[14].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[15].INV rosc_ref_ROSC_INV/genblk1.inv[15].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[16].INV rosc_ref_ROSC_INV/genblk1.inv[16].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[17].INV rosc_ref_ROSC_INV/genblk1.inv[17].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[18].INV rosc_ref_ROSC_INV/genblk1.inv[18].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[19].INV rosc_ref_ROSC_INV/genblk1.inv[19].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[20].INV rosc_ref_ROSC_INV/genblk1.inv[20].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[21].INV rosc_ref_ROSC_INV/genblk1.inv[21].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[22].INV rosc_ref_ROSC_INV/genblk1.inv[22].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[23].INV rosc_ref_ROSC_INV/genblk1.inv[23].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[24].INV rosc_ref_ROSC_INV/genblk1.inv[24].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[25].INV rosc_ref_ROSC_INV/genblk1.inv[25].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[26].INV rosc_ref_ROSC_INV/genblk1.inv[26].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[27].INV rosc_ref_ROSC_INV/genblk1.inv[27].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[28].INV rosc_ref_ROSC_INV/genblk1.inv[28].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[29].INV rosc_ref_ROSC_INV/genblk1.inv[29].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[30].INV rosc_ref_ROSC_INV/genblk1.inv[30].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[31].INV rosc_ref_ROSC_INV/genblk1.inv[31].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[32].INV rosc_ref_ROSC_INV/genblk1.inv[32].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[33].INV rosc_ref_ROSC_INV/genblk1.inv[33].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[34].INV rosc_ref_ROSC_INV/genblk1.inv[34].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[35].INV rosc_ref_ROSC_INV/genblk1.inv[35].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[36].INV rosc_ref_ROSC_INV/genblk1.inv[36].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[37].INV rosc_ref_ROSC_INV/genblk1.inv[37].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[38].INV rosc_ref_ROSC_INV/genblk1.inv[38].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[39].INV rosc_ref_ROSC_INV/genblk1.inv[39].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[40].INV rosc_ref_ROSC_INV/genblk1.inv[40].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[41].INV rosc_ref_ROSC_INV/genblk1.inv[41].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[42].INV rosc_ref_ROSC_INV/genblk1.inv[42].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[43].INV rosc_ref_ROSC_INV/genblk1.inv[43].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[44].INV rosc_ref_ROSC_INV/genblk1.inv[44].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[45].INV rosc_ref_ROSC_INV/genblk1.inv[45].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[46].INV rosc_ref_ROSC_INV/genblk1.inv[46].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[47].INV rosc_ref_ROSC_INV/genblk1.inv[47].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[48].INV rosc_ref_ROSC_INV/genblk1.inv[48].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[49].INV rosc_ref_ROSC_INV/genblk1.inv[49].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[50].INV rosc_ref_ROSC_INV/genblk1.inv[50].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[51].INV rosc_ref_ROSC_INV/genblk1.inv[51].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[52].INV rosc_ref_ROSC_INV/genblk1.inv[52].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[53].INV rosc_ref_ROSC_INV/genblk1.inv[53].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[54].INV rosc_ref_ROSC_INV/genblk1.inv[54].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[55].INV rosc_ref_ROSC_INV/genblk1.inv[55].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[56].INV rosc_ref_ROSC_INV/genblk1.inv[56].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[57].INV rosc_ref_ROSC_INV/genblk1.inv[57].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[58].INV rosc_ref_ROSC_INV/genblk1.inv[58].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[59].INV rosc_ref_ROSC_INV/genblk1.inv[59].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[60].INV rosc_ref_ROSC_INV/genblk1.inv[60].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[61].INV rosc_ref_ROSC_INV/genblk1.inv[61].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[62].INV rosc_ref_ROSC_INV/genblk1.inv[62].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[63].INV rosc_ref_ROSC_INV/genblk1.inv[63].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[64].INV rosc_ref_ROSC_INV/genblk1.inv[64].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[65].INV rosc_ref_ROSC_INV/genblk1.inv[65].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[66].INV rosc_ref_ROSC_INV/genblk1.inv[66].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[67].INV rosc_ref_ROSC_INV/genblk1.inv[67].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[68].INV rosc_ref_ROSC_INV/genblk1.inv[68].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[69].INV rosc_ref_ROSC_INV/genblk1.inv[69].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[70].INV rosc_ref_ROSC_INV/genblk1.inv[70].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[71].INV rosc_ref_ROSC_INV/genblk1.inv[71].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[72].INV rosc_ref_ROSC_INV/genblk1.inv[72].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[73].INV rosc_ref_ROSC_INV/genblk1.inv[73].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[74].INV rosc_ref_ROSC_INV/genblk1.inv[74].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[75].INV rosc_ref_ROSC_INV/genblk1.inv[75].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[76].INV rosc_ref_ROSC_INV/genblk1.inv[76].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[77].INV rosc_ref_ROSC_INV/genblk1.inv[77].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[78].INV rosc_ref_ROSC_INV/genblk1.inv[78].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[79].INV rosc_ref_ROSC_INV/genblk1.inv[79].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[80].INV rosc_ref_ROSC_INV/genblk1.inv[80].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[81].INV rosc_ref_ROSC_INV/genblk1.inv[81].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[82].INV rosc_ref_ROSC_INV/genblk1.inv[82].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[83].INV rosc_ref_ROSC_INV/genblk1.inv[83].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[84].INV rosc_ref_ROSC_INV/genblk1.inv[84].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[85].INV rosc_ref_ROSC_INV/genblk1.inv[85].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[86].INV rosc_ref_ROSC_INV/genblk1.inv[86].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[87].INV rosc_ref_ROSC_INV/genblk1.inv[87].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[88].INV rosc_ref_ROSC_INV/genblk1.inv[88].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[89].INV rosc_ref_ROSC_INV/genblk1.inv[89].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[90].INV rosc_ref_ROSC_INV/genblk1.inv[90].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[91].INV rosc_ref_ROSC_INV/genblk1.inv[91].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[92].INV rosc_ref_ROSC_INV/genblk1.inv[92].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[93].INV rosc_ref_ROSC_INV/genblk1.inv[93].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[94].INV rosc_ref_ROSC_INV/genblk1.inv[94].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[95].INV rosc_ref_ROSC_INV/genblk1.inv[95].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[96].INV rosc_ref_ROSC_INV/genblk1.inv[96].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[97].INV rosc_ref_ROSC_INV/genblk1.inv[97].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[98].INV rosc_ref_ROSC_INV/genblk1.inv[98].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[99].INV rosc_ref_ROSC_INV/genblk1.inv[99].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[100].INV rosc_ref_ROSC_INV/genblk1.inv[100].INV
add mapped point rosc_ref/ROSC_INV/genblk1.inv[101].INV rosc_ref_ROSC_INV/genblk1.inv[101].INV
add mapped point rosc_ref/ROSC_NAND rosc_ref_ROSC_NAND
add mapped point rosc_ref/ROSC_NAND/TIEHI rosc_ref_ROSC_NAND/TIEHI
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[0].NAND rosc_ref_ROSC_NAND/genblk1.nd[0].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[1].NAND rosc_ref_ROSC_NAND/genblk1.nd[1].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[2].NAND rosc_ref_ROSC_NAND/genblk1.nd[2].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[3].NAND rosc_ref_ROSC_NAND/genblk1.nd[3].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[4].NAND rosc_ref_ROSC_NAND/genblk1.nd[4].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[5].NAND rosc_ref_ROSC_NAND/genblk1.nd[5].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[6].NAND rosc_ref_ROSC_NAND/genblk1.nd[6].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[7].NAND rosc_ref_ROSC_NAND/genblk1.nd[7].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[8].NAND rosc_ref_ROSC_NAND/genblk1.nd[8].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[9].NAND rosc_ref_ROSC_NAND/genblk1.nd[9].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[10].NAND rosc_ref_ROSC_NAND/genblk1.nd[10].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[11].NAND rosc_ref_ROSC_NAND/genblk1.nd[11].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[12].NAND rosc_ref_ROSC_NAND/genblk1.nd[12].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[13].NAND rosc_ref_ROSC_NAND/genblk1.nd[13].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[14].NAND rosc_ref_ROSC_NAND/genblk1.nd[14].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[15].NAND rosc_ref_ROSC_NAND/genblk1.nd[15].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[16].NAND rosc_ref_ROSC_NAND/genblk1.nd[16].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[17].NAND rosc_ref_ROSC_NAND/genblk1.nd[17].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[18].NAND rosc_ref_ROSC_NAND/genblk1.nd[18].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[19].NAND rosc_ref_ROSC_NAND/genblk1.nd[19].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[20].NAND rosc_ref_ROSC_NAND/genblk1.nd[20].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[21].NAND rosc_ref_ROSC_NAND/genblk1.nd[21].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[22].NAND rosc_ref_ROSC_NAND/genblk1.nd[22].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[23].NAND rosc_ref_ROSC_NAND/genblk1.nd[23].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[24].NAND rosc_ref_ROSC_NAND/genblk1.nd[24].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[25].NAND rosc_ref_ROSC_NAND/genblk1.nd[25].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[26].NAND rosc_ref_ROSC_NAND/genblk1.nd[26].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[27].NAND rosc_ref_ROSC_NAND/genblk1.nd[27].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[28].NAND rosc_ref_ROSC_NAND/genblk1.nd[28].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[29].NAND rosc_ref_ROSC_NAND/genblk1.nd[29].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[30].NAND rosc_ref_ROSC_NAND/genblk1.nd[30].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[31].NAND rosc_ref_ROSC_NAND/genblk1.nd[31].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[32].NAND rosc_ref_ROSC_NAND/genblk1.nd[32].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[33].NAND rosc_ref_ROSC_NAND/genblk1.nd[33].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[34].NAND rosc_ref_ROSC_NAND/genblk1.nd[34].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[35].NAND rosc_ref_ROSC_NAND/genblk1.nd[35].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[36].NAND rosc_ref_ROSC_NAND/genblk1.nd[36].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[37].NAND rosc_ref_ROSC_NAND/genblk1.nd[37].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[38].NAND rosc_ref_ROSC_NAND/genblk1.nd[38].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[39].NAND rosc_ref_ROSC_NAND/genblk1.nd[39].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[40].NAND rosc_ref_ROSC_NAND/genblk1.nd[40].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[41].NAND rosc_ref_ROSC_NAND/genblk1.nd[41].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[42].NAND rosc_ref_ROSC_NAND/genblk1.nd[42].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[43].NAND rosc_ref_ROSC_NAND/genblk1.nd[43].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[44].NAND rosc_ref_ROSC_NAND/genblk1.nd[44].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[45].NAND rosc_ref_ROSC_NAND/genblk1.nd[45].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[46].NAND rosc_ref_ROSC_NAND/genblk1.nd[46].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[47].NAND rosc_ref_ROSC_NAND/genblk1.nd[47].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[48].NAND rosc_ref_ROSC_NAND/genblk1.nd[48].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[49].NAND rosc_ref_ROSC_NAND/genblk1.nd[49].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[50].NAND rosc_ref_ROSC_NAND/genblk1.nd[50].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[51].NAND rosc_ref_ROSC_NAND/genblk1.nd[51].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[52].NAND rosc_ref_ROSC_NAND/genblk1.nd[52].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[53].NAND rosc_ref_ROSC_NAND/genblk1.nd[53].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[54].NAND rosc_ref_ROSC_NAND/genblk1.nd[54].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[55].NAND rosc_ref_ROSC_NAND/genblk1.nd[55].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[56].NAND rosc_ref_ROSC_NAND/genblk1.nd[56].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[57].NAND rosc_ref_ROSC_NAND/genblk1.nd[57].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[58].NAND rosc_ref_ROSC_NAND/genblk1.nd[58].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[59].NAND rosc_ref_ROSC_NAND/genblk1.nd[59].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[60].NAND rosc_ref_ROSC_NAND/genblk1.nd[60].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[61].NAND rosc_ref_ROSC_NAND/genblk1.nd[61].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[62].NAND rosc_ref_ROSC_NAND/genblk1.nd[62].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[63].NAND rosc_ref_ROSC_NAND/genblk1.nd[63].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[64].NAND rosc_ref_ROSC_NAND/genblk1.nd[64].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[65].NAND rosc_ref_ROSC_NAND/genblk1.nd[65].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[66].NAND rosc_ref_ROSC_NAND/genblk1.nd[66].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[67].NAND rosc_ref_ROSC_NAND/genblk1.nd[67].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[68].NAND rosc_ref_ROSC_NAND/genblk1.nd[68].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[69].NAND rosc_ref_ROSC_NAND/genblk1.nd[69].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[70].NAND rosc_ref_ROSC_NAND/genblk1.nd[70].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[71].NAND rosc_ref_ROSC_NAND/genblk1.nd[71].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[72].NAND rosc_ref_ROSC_NAND/genblk1.nd[72].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[73].NAND rosc_ref_ROSC_NAND/genblk1.nd[73].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[74].NAND rosc_ref_ROSC_NAND/genblk1.nd[74].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[75].NAND rosc_ref_ROSC_NAND/genblk1.nd[75].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[76].NAND rosc_ref_ROSC_NAND/genblk1.nd[76].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[77].NAND rosc_ref_ROSC_NAND/genblk1.nd[77].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[78].NAND rosc_ref_ROSC_NAND/genblk1.nd[78].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[79].NAND rosc_ref_ROSC_NAND/genblk1.nd[79].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[80].NAND rosc_ref_ROSC_NAND/genblk1.nd[80].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[81].NAND rosc_ref_ROSC_NAND/genblk1.nd[81].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[82].NAND rosc_ref_ROSC_NAND/genblk1.nd[82].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[83].NAND rosc_ref_ROSC_NAND/genblk1.nd[83].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[84].NAND rosc_ref_ROSC_NAND/genblk1.nd[84].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[85].NAND rosc_ref_ROSC_NAND/genblk1.nd[85].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[86].NAND rosc_ref_ROSC_NAND/genblk1.nd[86].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[87].NAND rosc_ref_ROSC_NAND/genblk1.nd[87].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[88].NAND rosc_ref_ROSC_NAND/genblk1.nd[88].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[89].NAND rosc_ref_ROSC_NAND/genblk1.nd[89].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[90].NAND rosc_ref_ROSC_NAND/genblk1.nd[90].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[91].NAND rosc_ref_ROSC_NAND/genblk1.nd[91].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[92].NAND rosc_ref_ROSC_NAND/genblk1.nd[92].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[93].NAND rosc_ref_ROSC_NAND/genblk1.nd[93].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[94].NAND rosc_ref_ROSC_NAND/genblk1.nd[94].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[95].NAND rosc_ref_ROSC_NAND/genblk1.nd[95].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[96].NAND rosc_ref_ROSC_NAND/genblk1.nd[96].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[97].NAND rosc_ref_ROSC_NAND/genblk1.nd[97].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[98].NAND rosc_ref_ROSC_NAND/genblk1.nd[98].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[99].NAND rosc_ref_ROSC_NAND/genblk1.nd[99].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[100].NAND rosc_ref_ROSC_NAND/genblk1.nd[100].NAND
add mapped point rosc_ref/ROSC_NAND/genblk1.nd[101].NAND rosc_ref_ROSC_NAND/genblk1.nd[101].NAND
add mapped point rosc_ref/ROSC_NOR rosc_ref_ROSC_NOR
add mapped point rosc_ref/ROSC_NOR/TIELO rosc_ref_ROSC_NOR/TIELO
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[0].NOR rosc_ref_ROSC_NOR/genblk1.nr[0].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[1].NOR rosc_ref_ROSC_NOR/genblk1.nr[1].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[2].NOR rosc_ref_ROSC_NOR/genblk1.nr[2].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[3].NOR rosc_ref_ROSC_NOR/genblk1.nr[3].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[4].NOR rosc_ref_ROSC_NOR/genblk1.nr[4].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[5].NOR rosc_ref_ROSC_NOR/genblk1.nr[5].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[6].NOR rosc_ref_ROSC_NOR/genblk1.nr[6].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[7].NOR rosc_ref_ROSC_NOR/genblk1.nr[7].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[8].NOR rosc_ref_ROSC_NOR/genblk1.nr[8].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[9].NOR rosc_ref_ROSC_NOR/genblk1.nr[9].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[10].NOR rosc_ref_ROSC_NOR/genblk1.nr[10].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[11].NOR rosc_ref_ROSC_NOR/genblk1.nr[11].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[12].NOR rosc_ref_ROSC_NOR/genblk1.nr[12].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[13].NOR rosc_ref_ROSC_NOR/genblk1.nr[13].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[14].NOR rosc_ref_ROSC_NOR/genblk1.nr[14].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[15].NOR rosc_ref_ROSC_NOR/genblk1.nr[15].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[16].NOR rosc_ref_ROSC_NOR/genblk1.nr[16].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[17].NOR rosc_ref_ROSC_NOR/genblk1.nr[17].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[18].NOR rosc_ref_ROSC_NOR/genblk1.nr[18].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[19].NOR rosc_ref_ROSC_NOR/genblk1.nr[19].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[20].NOR rosc_ref_ROSC_NOR/genblk1.nr[20].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[21].NOR rosc_ref_ROSC_NOR/genblk1.nr[21].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[22].NOR rosc_ref_ROSC_NOR/genblk1.nr[22].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[23].NOR rosc_ref_ROSC_NOR/genblk1.nr[23].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[24].NOR rosc_ref_ROSC_NOR/genblk1.nr[24].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[25].NOR rosc_ref_ROSC_NOR/genblk1.nr[25].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[26].NOR rosc_ref_ROSC_NOR/genblk1.nr[26].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[27].NOR rosc_ref_ROSC_NOR/genblk1.nr[27].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[28].NOR rosc_ref_ROSC_NOR/genblk1.nr[28].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[29].NOR rosc_ref_ROSC_NOR/genblk1.nr[29].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[30].NOR rosc_ref_ROSC_NOR/genblk1.nr[30].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[31].NOR rosc_ref_ROSC_NOR/genblk1.nr[31].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[32].NOR rosc_ref_ROSC_NOR/genblk1.nr[32].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[33].NOR rosc_ref_ROSC_NOR/genblk1.nr[33].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[34].NOR rosc_ref_ROSC_NOR/genblk1.nr[34].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[35].NOR rosc_ref_ROSC_NOR/genblk1.nr[35].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[36].NOR rosc_ref_ROSC_NOR/genblk1.nr[36].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[37].NOR rosc_ref_ROSC_NOR/genblk1.nr[37].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[38].NOR rosc_ref_ROSC_NOR/genblk1.nr[38].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[39].NOR rosc_ref_ROSC_NOR/genblk1.nr[39].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[40].NOR rosc_ref_ROSC_NOR/genblk1.nr[40].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[41].NOR rosc_ref_ROSC_NOR/genblk1.nr[41].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[42].NOR rosc_ref_ROSC_NOR/genblk1.nr[42].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[43].NOR rosc_ref_ROSC_NOR/genblk1.nr[43].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[44].NOR rosc_ref_ROSC_NOR/genblk1.nr[44].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[45].NOR rosc_ref_ROSC_NOR/genblk1.nr[45].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[46].NOR rosc_ref_ROSC_NOR/genblk1.nr[46].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[47].NOR rosc_ref_ROSC_NOR/genblk1.nr[47].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[48].NOR rosc_ref_ROSC_NOR/genblk1.nr[48].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[49].NOR rosc_ref_ROSC_NOR/genblk1.nr[49].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[50].NOR rosc_ref_ROSC_NOR/genblk1.nr[50].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[51].NOR rosc_ref_ROSC_NOR/genblk1.nr[51].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[52].NOR rosc_ref_ROSC_NOR/genblk1.nr[52].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[53].NOR rosc_ref_ROSC_NOR/genblk1.nr[53].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[54].NOR rosc_ref_ROSC_NOR/genblk1.nr[54].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[55].NOR rosc_ref_ROSC_NOR/genblk1.nr[55].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[56].NOR rosc_ref_ROSC_NOR/genblk1.nr[56].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[57].NOR rosc_ref_ROSC_NOR/genblk1.nr[57].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[58].NOR rosc_ref_ROSC_NOR/genblk1.nr[58].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[59].NOR rosc_ref_ROSC_NOR/genblk1.nr[59].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[60].NOR rosc_ref_ROSC_NOR/genblk1.nr[60].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[61].NOR rosc_ref_ROSC_NOR/genblk1.nr[61].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[62].NOR rosc_ref_ROSC_NOR/genblk1.nr[62].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[63].NOR rosc_ref_ROSC_NOR/genblk1.nr[63].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[64].NOR rosc_ref_ROSC_NOR/genblk1.nr[64].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[65].NOR rosc_ref_ROSC_NOR/genblk1.nr[65].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[66].NOR rosc_ref_ROSC_NOR/genblk1.nr[66].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[67].NOR rosc_ref_ROSC_NOR/genblk1.nr[67].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[68].NOR rosc_ref_ROSC_NOR/genblk1.nr[68].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[69].NOR rosc_ref_ROSC_NOR/genblk1.nr[69].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[70].NOR rosc_ref_ROSC_NOR/genblk1.nr[70].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[71].NOR rosc_ref_ROSC_NOR/genblk1.nr[71].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[72].NOR rosc_ref_ROSC_NOR/genblk1.nr[72].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[73].NOR rosc_ref_ROSC_NOR/genblk1.nr[73].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[74].NOR rosc_ref_ROSC_NOR/genblk1.nr[74].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[75].NOR rosc_ref_ROSC_NOR/genblk1.nr[75].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[76].NOR rosc_ref_ROSC_NOR/genblk1.nr[76].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[77].NOR rosc_ref_ROSC_NOR/genblk1.nr[77].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[78].NOR rosc_ref_ROSC_NOR/genblk1.nr[78].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[79].NOR rosc_ref_ROSC_NOR/genblk1.nr[79].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[80].NOR rosc_ref_ROSC_NOR/genblk1.nr[80].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[81].NOR rosc_ref_ROSC_NOR/genblk1.nr[81].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[82].NOR rosc_ref_ROSC_NOR/genblk1.nr[82].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[83].NOR rosc_ref_ROSC_NOR/genblk1.nr[83].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[84].NOR rosc_ref_ROSC_NOR/genblk1.nr[84].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[85].NOR rosc_ref_ROSC_NOR/genblk1.nr[85].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[86].NOR rosc_ref_ROSC_NOR/genblk1.nr[86].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[87].NOR rosc_ref_ROSC_NOR/genblk1.nr[87].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[88].NOR rosc_ref_ROSC_NOR/genblk1.nr[88].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[89].NOR rosc_ref_ROSC_NOR/genblk1.nr[89].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[90].NOR rosc_ref_ROSC_NOR/genblk1.nr[90].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[91].NOR rosc_ref_ROSC_NOR/genblk1.nr[91].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[92].NOR rosc_ref_ROSC_NOR/genblk1.nr[92].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[93].NOR rosc_ref_ROSC_NOR/genblk1.nr[93].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[94].NOR rosc_ref_ROSC_NOR/genblk1.nr[94].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[95].NOR rosc_ref_ROSC_NOR/genblk1.nr[95].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[96].NOR rosc_ref_ROSC_NOR/genblk1.nr[96].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[97].NOR rosc_ref_ROSC_NOR/genblk1.nr[97].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[98].NOR rosc_ref_ROSC_NOR/genblk1.nr[98].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[99].NOR rosc_ref_ROSC_NOR/genblk1.nr[99].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[100].NOR rosc_ref_ROSC_NOR/genblk1.nr[100].NOR
add mapped point rosc_ref/ROSC_NOR/genblk1.nr[101].NOR rosc_ref_ROSC_NOR/genblk1.nr[101].NOR
add mapped point rosc_ref/rosc_control/pwr_NAND rosc_ref_rosc_control_pwr_NAND
add mapped point rosc_ref/rosc_control/pwr_NAND/AND2_OFF rosc_ref_rosc_control_pwr_NAND/AND2_OFF
add mapped point rosc_ref/rosc_control/pwr_NAND/INV rosc_ref_rosc_control_pwr_NAND/INV
add mapped point rosc_ref/rosc_control/pwr_NAND/INV8_base_1 rosc_ref_rosc_control_pwr_NAND/INV8_base_1
add mapped point rosc_ref/rosc_control/pwr_NAND/INV8_base_2 rosc_ref_rosc_control_pwr_NAND/INV8_base_2
add mapped point rosc_ref/rosc_control/pwr_NAND/INV8_base_3 rosc_ref_rosc_control_pwr_NAND/INV8_base_3
add mapped point rosc_ref/rosc_control/pwr_NAND/INV8_base_4 rosc_ref_rosc_control_pwr_NAND/INV8_base_4
add mapped point rosc_ref/rosc_control/pwr_NOR rosc_ref_rosc_control_pwr_NOR
add mapped point rosc_ref/rosc_control/pwr_NOR/AND2_OFF rosc_ref_rosc_control_pwr_NOR/AND2_OFF
add mapped point rosc_ref/rosc_control/pwr_NOR/INV rosc_ref_rosc_control_pwr_NOR/INV
add mapped point rosc_ref/rosc_control/pwr_NOR/INV8_base_1 rosc_ref_rosc_control_pwr_NOR/INV8_base_1
add mapped point rosc_ref/rosc_control/pwr_NOR/INV8_base_2 rosc_ref_rosc_control_pwr_NOR/INV8_base_2
add mapped point rosc_ref/rosc_control/pwr_NOR/INV8_base_3 rosc_ref_rosc_control_pwr_NOR/INV8_base_3
add mapped point rosc_ref/rosc_control/pwr_NOR/INV8_base_4 rosc_ref_rosc_control_pwr_NOR/INV8_base_4
add mapped point rosc_ref/rosc_control/pwr_inv rosc_ref_rosc_control_pwr_inv
add mapped point rosc_ref/rosc_control/pwr_inv/AND2_OFF rosc_ref_rosc_control_pwr_inv/AND2_OFF
add mapped point rosc_ref/rosc_control/pwr_inv/INV rosc_ref_rosc_control_pwr_inv/INV
add mapped point rosc_ref/rosc_control/pwr_inv/INV8_base_1 rosc_ref_rosc_control_pwr_inv/INV8_base_1
add mapped point rosc_ref/rosc_control/pwr_inv/INV8_base_2 rosc_ref_rosc_control_pwr_inv/INV8_base_2
add mapped point rosc_ref/rosc_control/pwr_inv/INV8_base_3 rosc_ref_rosc_control_pwr_inv/INV8_base_3
add mapped point rosc_ref/rosc_control/pwr_inv/INV8_base_4 rosc_ref_rosc_control_pwr_inv/INV8_base_4
add mapped point rosc_stress/ROSC_INV rosc_stress_ROSC_INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[0].INV rosc_stress_ROSC_INV/genblk1.inv[0].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[1].INV rosc_stress_ROSC_INV/genblk1.inv[1].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[2].INV rosc_stress_ROSC_INV/genblk1.inv[2].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[3].INV rosc_stress_ROSC_INV/genblk1.inv[3].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[4].INV rosc_stress_ROSC_INV/genblk1.inv[4].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[5].INV rosc_stress_ROSC_INV/genblk1.inv[5].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[6].INV rosc_stress_ROSC_INV/genblk1.inv[6].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[7].INV rosc_stress_ROSC_INV/genblk1.inv[7].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[8].INV rosc_stress_ROSC_INV/genblk1.inv[8].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[9].INV rosc_stress_ROSC_INV/genblk1.inv[9].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[10].INV rosc_stress_ROSC_INV/genblk1.inv[10].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[11].INV rosc_stress_ROSC_INV/genblk1.inv[11].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[12].INV rosc_stress_ROSC_INV/genblk1.inv[12].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[13].INV rosc_stress_ROSC_INV/genblk1.inv[13].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[14].INV rosc_stress_ROSC_INV/genblk1.inv[14].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[15].INV rosc_stress_ROSC_INV/genblk1.inv[15].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[16].INV rosc_stress_ROSC_INV/genblk1.inv[16].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[17].INV rosc_stress_ROSC_INV/genblk1.inv[17].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[18].INV rosc_stress_ROSC_INV/genblk1.inv[18].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[19].INV rosc_stress_ROSC_INV/genblk1.inv[19].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[20].INV rosc_stress_ROSC_INV/genblk1.inv[20].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[21].INV rosc_stress_ROSC_INV/genblk1.inv[21].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[22].INV rosc_stress_ROSC_INV/genblk1.inv[22].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[23].INV rosc_stress_ROSC_INV/genblk1.inv[23].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[24].INV rosc_stress_ROSC_INV/genblk1.inv[24].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[25].INV rosc_stress_ROSC_INV/genblk1.inv[25].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[26].INV rosc_stress_ROSC_INV/genblk1.inv[26].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[27].INV rosc_stress_ROSC_INV/genblk1.inv[27].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[28].INV rosc_stress_ROSC_INV/genblk1.inv[28].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[29].INV rosc_stress_ROSC_INV/genblk1.inv[29].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[30].INV rosc_stress_ROSC_INV/genblk1.inv[30].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[31].INV rosc_stress_ROSC_INV/genblk1.inv[31].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[32].INV rosc_stress_ROSC_INV/genblk1.inv[32].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[33].INV rosc_stress_ROSC_INV/genblk1.inv[33].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[34].INV rosc_stress_ROSC_INV/genblk1.inv[34].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[35].INV rosc_stress_ROSC_INV/genblk1.inv[35].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[36].INV rosc_stress_ROSC_INV/genblk1.inv[36].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[37].INV rosc_stress_ROSC_INV/genblk1.inv[37].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[38].INV rosc_stress_ROSC_INV/genblk1.inv[38].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[39].INV rosc_stress_ROSC_INV/genblk1.inv[39].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[40].INV rosc_stress_ROSC_INV/genblk1.inv[40].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[41].INV rosc_stress_ROSC_INV/genblk1.inv[41].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[42].INV rosc_stress_ROSC_INV/genblk1.inv[42].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[43].INV rosc_stress_ROSC_INV/genblk1.inv[43].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[44].INV rosc_stress_ROSC_INV/genblk1.inv[44].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[45].INV rosc_stress_ROSC_INV/genblk1.inv[45].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[46].INV rosc_stress_ROSC_INV/genblk1.inv[46].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[47].INV rosc_stress_ROSC_INV/genblk1.inv[47].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[48].INV rosc_stress_ROSC_INV/genblk1.inv[48].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[49].INV rosc_stress_ROSC_INV/genblk1.inv[49].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[50].INV rosc_stress_ROSC_INV/genblk1.inv[50].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[51].INV rosc_stress_ROSC_INV/genblk1.inv[51].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[52].INV rosc_stress_ROSC_INV/genblk1.inv[52].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[53].INV rosc_stress_ROSC_INV/genblk1.inv[53].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[54].INV rosc_stress_ROSC_INV/genblk1.inv[54].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[55].INV rosc_stress_ROSC_INV/genblk1.inv[55].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[56].INV rosc_stress_ROSC_INV/genblk1.inv[56].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[57].INV rosc_stress_ROSC_INV/genblk1.inv[57].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[58].INV rosc_stress_ROSC_INV/genblk1.inv[58].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[59].INV rosc_stress_ROSC_INV/genblk1.inv[59].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[60].INV rosc_stress_ROSC_INV/genblk1.inv[60].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[61].INV rosc_stress_ROSC_INV/genblk1.inv[61].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[62].INV rosc_stress_ROSC_INV/genblk1.inv[62].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[63].INV rosc_stress_ROSC_INV/genblk1.inv[63].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[64].INV rosc_stress_ROSC_INV/genblk1.inv[64].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[65].INV rosc_stress_ROSC_INV/genblk1.inv[65].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[66].INV rosc_stress_ROSC_INV/genblk1.inv[66].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[67].INV rosc_stress_ROSC_INV/genblk1.inv[67].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[68].INV rosc_stress_ROSC_INV/genblk1.inv[68].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[69].INV rosc_stress_ROSC_INV/genblk1.inv[69].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[70].INV rosc_stress_ROSC_INV/genblk1.inv[70].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[71].INV rosc_stress_ROSC_INV/genblk1.inv[71].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[72].INV rosc_stress_ROSC_INV/genblk1.inv[72].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[73].INV rosc_stress_ROSC_INV/genblk1.inv[73].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[74].INV rosc_stress_ROSC_INV/genblk1.inv[74].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[75].INV rosc_stress_ROSC_INV/genblk1.inv[75].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[76].INV rosc_stress_ROSC_INV/genblk1.inv[76].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[77].INV rosc_stress_ROSC_INV/genblk1.inv[77].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[78].INV rosc_stress_ROSC_INV/genblk1.inv[78].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[79].INV rosc_stress_ROSC_INV/genblk1.inv[79].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[80].INV rosc_stress_ROSC_INV/genblk1.inv[80].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[81].INV rosc_stress_ROSC_INV/genblk1.inv[81].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[82].INV rosc_stress_ROSC_INV/genblk1.inv[82].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[83].INV rosc_stress_ROSC_INV/genblk1.inv[83].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[84].INV rosc_stress_ROSC_INV/genblk1.inv[84].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[85].INV rosc_stress_ROSC_INV/genblk1.inv[85].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[86].INV rosc_stress_ROSC_INV/genblk1.inv[86].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[87].INV rosc_stress_ROSC_INV/genblk1.inv[87].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[88].INV rosc_stress_ROSC_INV/genblk1.inv[88].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[89].INV rosc_stress_ROSC_INV/genblk1.inv[89].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[90].INV rosc_stress_ROSC_INV/genblk1.inv[90].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[91].INV rosc_stress_ROSC_INV/genblk1.inv[91].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[92].INV rosc_stress_ROSC_INV/genblk1.inv[92].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[93].INV rosc_stress_ROSC_INV/genblk1.inv[93].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[94].INV rosc_stress_ROSC_INV/genblk1.inv[94].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[95].INV rosc_stress_ROSC_INV/genblk1.inv[95].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[96].INV rosc_stress_ROSC_INV/genblk1.inv[96].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[97].INV rosc_stress_ROSC_INV/genblk1.inv[97].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[98].INV rosc_stress_ROSC_INV/genblk1.inv[98].INV
add mapped point rosc_stress/ROSC_INV/genblk1.inv[99].INV rosc_stress_ROSC_INV/genblk1.inv[99].INV
add mapped point rosc_stress/ROSC_NAND rosc_stress_ROSC_NAND
add mapped point rosc_stress/ROSC_NAND/TIEHI rosc_stress_ROSC_NAND/TIEHI
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[0].NAND rosc_stress_ROSC_NAND/genblk1.nd[0].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[1].NAND rosc_stress_ROSC_NAND/genblk1.nd[1].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[2].NAND rosc_stress_ROSC_NAND/genblk1.nd[2].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[3].NAND rosc_stress_ROSC_NAND/genblk1.nd[3].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[4].NAND rosc_stress_ROSC_NAND/genblk1.nd[4].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[5].NAND rosc_stress_ROSC_NAND/genblk1.nd[5].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[6].NAND rosc_stress_ROSC_NAND/genblk1.nd[6].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[7].NAND rosc_stress_ROSC_NAND/genblk1.nd[7].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[8].NAND rosc_stress_ROSC_NAND/genblk1.nd[8].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[9].NAND rosc_stress_ROSC_NAND/genblk1.nd[9].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[10].NAND rosc_stress_ROSC_NAND/genblk1.nd[10].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[11].NAND rosc_stress_ROSC_NAND/genblk1.nd[11].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[12].NAND rosc_stress_ROSC_NAND/genblk1.nd[12].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[13].NAND rosc_stress_ROSC_NAND/genblk1.nd[13].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[14].NAND rosc_stress_ROSC_NAND/genblk1.nd[14].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[15].NAND rosc_stress_ROSC_NAND/genblk1.nd[15].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[16].NAND rosc_stress_ROSC_NAND/genblk1.nd[16].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[17].NAND rosc_stress_ROSC_NAND/genblk1.nd[17].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[18].NAND rosc_stress_ROSC_NAND/genblk1.nd[18].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[19].NAND rosc_stress_ROSC_NAND/genblk1.nd[19].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[20].NAND rosc_stress_ROSC_NAND/genblk1.nd[20].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[21].NAND rosc_stress_ROSC_NAND/genblk1.nd[21].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[22].NAND rosc_stress_ROSC_NAND/genblk1.nd[22].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[23].NAND rosc_stress_ROSC_NAND/genblk1.nd[23].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[24].NAND rosc_stress_ROSC_NAND/genblk1.nd[24].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[25].NAND rosc_stress_ROSC_NAND/genblk1.nd[25].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[26].NAND rosc_stress_ROSC_NAND/genblk1.nd[26].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[27].NAND rosc_stress_ROSC_NAND/genblk1.nd[27].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[28].NAND rosc_stress_ROSC_NAND/genblk1.nd[28].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[29].NAND rosc_stress_ROSC_NAND/genblk1.nd[29].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[30].NAND rosc_stress_ROSC_NAND/genblk1.nd[30].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[31].NAND rosc_stress_ROSC_NAND/genblk1.nd[31].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[32].NAND rosc_stress_ROSC_NAND/genblk1.nd[32].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[33].NAND rosc_stress_ROSC_NAND/genblk1.nd[33].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[34].NAND rosc_stress_ROSC_NAND/genblk1.nd[34].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[35].NAND rosc_stress_ROSC_NAND/genblk1.nd[35].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[36].NAND rosc_stress_ROSC_NAND/genblk1.nd[36].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[37].NAND rosc_stress_ROSC_NAND/genblk1.nd[37].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[38].NAND rosc_stress_ROSC_NAND/genblk1.nd[38].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[39].NAND rosc_stress_ROSC_NAND/genblk1.nd[39].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[40].NAND rosc_stress_ROSC_NAND/genblk1.nd[40].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[41].NAND rosc_stress_ROSC_NAND/genblk1.nd[41].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[42].NAND rosc_stress_ROSC_NAND/genblk1.nd[42].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[43].NAND rosc_stress_ROSC_NAND/genblk1.nd[43].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[44].NAND rosc_stress_ROSC_NAND/genblk1.nd[44].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[45].NAND rosc_stress_ROSC_NAND/genblk1.nd[45].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[46].NAND rosc_stress_ROSC_NAND/genblk1.nd[46].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[47].NAND rosc_stress_ROSC_NAND/genblk1.nd[47].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[48].NAND rosc_stress_ROSC_NAND/genblk1.nd[48].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[49].NAND rosc_stress_ROSC_NAND/genblk1.nd[49].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[50].NAND rosc_stress_ROSC_NAND/genblk1.nd[50].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[51].NAND rosc_stress_ROSC_NAND/genblk1.nd[51].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[52].NAND rosc_stress_ROSC_NAND/genblk1.nd[52].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[53].NAND rosc_stress_ROSC_NAND/genblk1.nd[53].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[54].NAND rosc_stress_ROSC_NAND/genblk1.nd[54].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[55].NAND rosc_stress_ROSC_NAND/genblk1.nd[55].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[56].NAND rosc_stress_ROSC_NAND/genblk1.nd[56].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[57].NAND rosc_stress_ROSC_NAND/genblk1.nd[57].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[58].NAND rosc_stress_ROSC_NAND/genblk1.nd[58].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[59].NAND rosc_stress_ROSC_NAND/genblk1.nd[59].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[60].NAND rosc_stress_ROSC_NAND/genblk1.nd[60].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[61].NAND rosc_stress_ROSC_NAND/genblk1.nd[61].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[62].NAND rosc_stress_ROSC_NAND/genblk1.nd[62].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[63].NAND rosc_stress_ROSC_NAND/genblk1.nd[63].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[64].NAND rosc_stress_ROSC_NAND/genblk1.nd[64].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[65].NAND rosc_stress_ROSC_NAND/genblk1.nd[65].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[66].NAND rosc_stress_ROSC_NAND/genblk1.nd[66].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[67].NAND rosc_stress_ROSC_NAND/genblk1.nd[67].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[68].NAND rosc_stress_ROSC_NAND/genblk1.nd[68].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[69].NAND rosc_stress_ROSC_NAND/genblk1.nd[69].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[70].NAND rosc_stress_ROSC_NAND/genblk1.nd[70].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[71].NAND rosc_stress_ROSC_NAND/genblk1.nd[71].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[72].NAND rosc_stress_ROSC_NAND/genblk1.nd[72].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[73].NAND rosc_stress_ROSC_NAND/genblk1.nd[73].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[74].NAND rosc_stress_ROSC_NAND/genblk1.nd[74].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[75].NAND rosc_stress_ROSC_NAND/genblk1.nd[75].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[76].NAND rosc_stress_ROSC_NAND/genblk1.nd[76].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[77].NAND rosc_stress_ROSC_NAND/genblk1.nd[77].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[78].NAND rosc_stress_ROSC_NAND/genblk1.nd[78].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[79].NAND rosc_stress_ROSC_NAND/genblk1.nd[79].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[80].NAND rosc_stress_ROSC_NAND/genblk1.nd[80].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[81].NAND rosc_stress_ROSC_NAND/genblk1.nd[81].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[82].NAND rosc_stress_ROSC_NAND/genblk1.nd[82].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[83].NAND rosc_stress_ROSC_NAND/genblk1.nd[83].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[84].NAND rosc_stress_ROSC_NAND/genblk1.nd[84].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[85].NAND rosc_stress_ROSC_NAND/genblk1.nd[85].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[86].NAND rosc_stress_ROSC_NAND/genblk1.nd[86].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[87].NAND rosc_stress_ROSC_NAND/genblk1.nd[87].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[88].NAND rosc_stress_ROSC_NAND/genblk1.nd[88].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[89].NAND rosc_stress_ROSC_NAND/genblk1.nd[89].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[90].NAND rosc_stress_ROSC_NAND/genblk1.nd[90].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[91].NAND rosc_stress_ROSC_NAND/genblk1.nd[91].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[92].NAND rosc_stress_ROSC_NAND/genblk1.nd[92].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[93].NAND rosc_stress_ROSC_NAND/genblk1.nd[93].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[94].NAND rosc_stress_ROSC_NAND/genblk1.nd[94].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[95].NAND rosc_stress_ROSC_NAND/genblk1.nd[95].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[96].NAND rosc_stress_ROSC_NAND/genblk1.nd[96].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[97].NAND rosc_stress_ROSC_NAND/genblk1.nd[97].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[98].NAND rosc_stress_ROSC_NAND/genblk1.nd[98].NAND
add mapped point rosc_stress/ROSC_NAND/genblk1.nd[99].NAND rosc_stress_ROSC_NAND/genblk1.nd[99].NAND
add mapped point rosc_stress/ROSC_NOR rosc_stress_ROSC_NOR
add mapped point rosc_stress/ROSC_NOR/TIELO rosc_stress_ROSC_NOR/TIELO
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[0].NOR rosc_stress_ROSC_NOR/genblk1.nr[0].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[1].NOR rosc_stress_ROSC_NOR/genblk1.nr[1].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[2].NOR rosc_stress_ROSC_NOR/genblk1.nr[2].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[3].NOR rosc_stress_ROSC_NOR/genblk1.nr[3].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[4].NOR rosc_stress_ROSC_NOR/genblk1.nr[4].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[5].NOR rosc_stress_ROSC_NOR/genblk1.nr[5].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[6].NOR rosc_stress_ROSC_NOR/genblk1.nr[6].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[7].NOR rosc_stress_ROSC_NOR/genblk1.nr[7].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[8].NOR rosc_stress_ROSC_NOR/genblk1.nr[8].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[9].NOR rosc_stress_ROSC_NOR/genblk1.nr[9].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[10].NOR rosc_stress_ROSC_NOR/genblk1.nr[10].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[11].NOR rosc_stress_ROSC_NOR/genblk1.nr[11].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[12].NOR rosc_stress_ROSC_NOR/genblk1.nr[12].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[13].NOR rosc_stress_ROSC_NOR/genblk1.nr[13].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[14].NOR rosc_stress_ROSC_NOR/genblk1.nr[14].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[15].NOR rosc_stress_ROSC_NOR/genblk1.nr[15].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[16].NOR rosc_stress_ROSC_NOR/genblk1.nr[16].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[17].NOR rosc_stress_ROSC_NOR/genblk1.nr[17].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[18].NOR rosc_stress_ROSC_NOR/genblk1.nr[18].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[19].NOR rosc_stress_ROSC_NOR/genblk1.nr[19].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[20].NOR rosc_stress_ROSC_NOR/genblk1.nr[20].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[21].NOR rosc_stress_ROSC_NOR/genblk1.nr[21].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[22].NOR rosc_stress_ROSC_NOR/genblk1.nr[22].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[23].NOR rosc_stress_ROSC_NOR/genblk1.nr[23].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[24].NOR rosc_stress_ROSC_NOR/genblk1.nr[24].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[25].NOR rosc_stress_ROSC_NOR/genblk1.nr[25].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[26].NOR rosc_stress_ROSC_NOR/genblk1.nr[26].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[27].NOR rosc_stress_ROSC_NOR/genblk1.nr[27].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[28].NOR rosc_stress_ROSC_NOR/genblk1.nr[28].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[29].NOR rosc_stress_ROSC_NOR/genblk1.nr[29].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[30].NOR rosc_stress_ROSC_NOR/genblk1.nr[30].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[31].NOR rosc_stress_ROSC_NOR/genblk1.nr[31].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[32].NOR rosc_stress_ROSC_NOR/genblk1.nr[32].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[33].NOR rosc_stress_ROSC_NOR/genblk1.nr[33].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[34].NOR rosc_stress_ROSC_NOR/genblk1.nr[34].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[35].NOR rosc_stress_ROSC_NOR/genblk1.nr[35].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[36].NOR rosc_stress_ROSC_NOR/genblk1.nr[36].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[37].NOR rosc_stress_ROSC_NOR/genblk1.nr[37].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[38].NOR rosc_stress_ROSC_NOR/genblk1.nr[38].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[39].NOR rosc_stress_ROSC_NOR/genblk1.nr[39].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[40].NOR rosc_stress_ROSC_NOR/genblk1.nr[40].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[41].NOR rosc_stress_ROSC_NOR/genblk1.nr[41].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[42].NOR rosc_stress_ROSC_NOR/genblk1.nr[42].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[43].NOR rosc_stress_ROSC_NOR/genblk1.nr[43].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[44].NOR rosc_stress_ROSC_NOR/genblk1.nr[44].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[45].NOR rosc_stress_ROSC_NOR/genblk1.nr[45].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[46].NOR rosc_stress_ROSC_NOR/genblk1.nr[46].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[47].NOR rosc_stress_ROSC_NOR/genblk1.nr[47].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[48].NOR rosc_stress_ROSC_NOR/genblk1.nr[48].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[49].NOR rosc_stress_ROSC_NOR/genblk1.nr[49].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[50].NOR rosc_stress_ROSC_NOR/genblk1.nr[50].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[51].NOR rosc_stress_ROSC_NOR/genblk1.nr[51].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[52].NOR rosc_stress_ROSC_NOR/genblk1.nr[52].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[53].NOR rosc_stress_ROSC_NOR/genblk1.nr[53].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[54].NOR rosc_stress_ROSC_NOR/genblk1.nr[54].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[55].NOR rosc_stress_ROSC_NOR/genblk1.nr[55].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[56].NOR rosc_stress_ROSC_NOR/genblk1.nr[56].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[57].NOR rosc_stress_ROSC_NOR/genblk1.nr[57].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[58].NOR rosc_stress_ROSC_NOR/genblk1.nr[58].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[59].NOR rosc_stress_ROSC_NOR/genblk1.nr[59].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[60].NOR rosc_stress_ROSC_NOR/genblk1.nr[60].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[61].NOR rosc_stress_ROSC_NOR/genblk1.nr[61].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[62].NOR rosc_stress_ROSC_NOR/genblk1.nr[62].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[63].NOR rosc_stress_ROSC_NOR/genblk1.nr[63].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[64].NOR rosc_stress_ROSC_NOR/genblk1.nr[64].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[65].NOR rosc_stress_ROSC_NOR/genblk1.nr[65].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[66].NOR rosc_stress_ROSC_NOR/genblk1.nr[66].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[67].NOR rosc_stress_ROSC_NOR/genblk1.nr[67].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[68].NOR rosc_stress_ROSC_NOR/genblk1.nr[68].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[69].NOR rosc_stress_ROSC_NOR/genblk1.nr[69].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[70].NOR rosc_stress_ROSC_NOR/genblk1.nr[70].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[71].NOR rosc_stress_ROSC_NOR/genblk1.nr[71].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[72].NOR rosc_stress_ROSC_NOR/genblk1.nr[72].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[73].NOR rosc_stress_ROSC_NOR/genblk1.nr[73].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[74].NOR rosc_stress_ROSC_NOR/genblk1.nr[74].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[75].NOR rosc_stress_ROSC_NOR/genblk1.nr[75].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[76].NOR rosc_stress_ROSC_NOR/genblk1.nr[76].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[77].NOR rosc_stress_ROSC_NOR/genblk1.nr[77].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[78].NOR rosc_stress_ROSC_NOR/genblk1.nr[78].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[79].NOR rosc_stress_ROSC_NOR/genblk1.nr[79].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[80].NOR rosc_stress_ROSC_NOR/genblk1.nr[80].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[81].NOR rosc_stress_ROSC_NOR/genblk1.nr[81].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[82].NOR rosc_stress_ROSC_NOR/genblk1.nr[82].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[83].NOR rosc_stress_ROSC_NOR/genblk1.nr[83].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[84].NOR rosc_stress_ROSC_NOR/genblk1.nr[84].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[85].NOR rosc_stress_ROSC_NOR/genblk1.nr[85].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[86].NOR rosc_stress_ROSC_NOR/genblk1.nr[86].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[87].NOR rosc_stress_ROSC_NOR/genblk1.nr[87].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[88].NOR rosc_stress_ROSC_NOR/genblk1.nr[88].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[89].NOR rosc_stress_ROSC_NOR/genblk1.nr[89].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[90].NOR rosc_stress_ROSC_NOR/genblk1.nr[90].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[91].NOR rosc_stress_ROSC_NOR/genblk1.nr[91].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[92].NOR rosc_stress_ROSC_NOR/genblk1.nr[92].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[93].NOR rosc_stress_ROSC_NOR/genblk1.nr[93].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[94].NOR rosc_stress_ROSC_NOR/genblk1.nr[94].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[95].NOR rosc_stress_ROSC_NOR/genblk1.nr[95].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[96].NOR rosc_stress_ROSC_NOR/genblk1.nr[96].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[97].NOR rosc_stress_ROSC_NOR/genblk1.nr[97].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[98].NOR rosc_stress_ROSC_NOR/genblk1.nr[98].NOR
add mapped point rosc_stress/ROSC_NOR/genblk1.nr[99].NOR rosc_stress_ROSC_NOR/genblk1.nr[99].NOR
add mapped point rosc_stress/rosc_control/pwr_NAND rosc_stress_rosc_control_pwr_NAND
add mapped point rosc_stress/rosc_control/pwr_NAND/AND2_OFF rosc_stress_rosc_control_pwr_NAND/AND2_OFF
add mapped point rosc_stress/rosc_control/pwr_NAND/INV rosc_stress_rosc_control_pwr_NAND/INV
add mapped point rosc_stress/rosc_control/pwr_NAND/INV8_base_1 rosc_stress_rosc_control_pwr_NAND/INV8_base_1
add mapped point rosc_stress/rosc_control/pwr_NAND/INV8_base_2 rosc_stress_rosc_control_pwr_NAND/INV8_base_2
add mapped point rosc_stress/rosc_control/pwr_NAND/INV8_base_3 rosc_stress_rosc_control_pwr_NAND/INV8_base_3
add mapped point rosc_stress/rosc_control/pwr_NAND/INV8_base_4 rosc_stress_rosc_control_pwr_NAND/INV8_base_4
add mapped point rosc_stress/rosc_control/pwr_NOR rosc_stress_rosc_control_pwr_NOR
add mapped point rosc_stress/rosc_control/pwr_NOR/AND2_OFF rosc_stress_rosc_control_pwr_NOR/AND2_OFF
add mapped point rosc_stress/rosc_control/pwr_NOR/INV rosc_stress_rosc_control_pwr_NOR/INV
add mapped point rosc_stress/rosc_control/pwr_NOR/INV8_base_1 rosc_stress_rosc_control_pwr_NOR/INV8_base_1
add mapped point rosc_stress/rosc_control/pwr_NOR/INV8_base_2 rosc_stress_rosc_control_pwr_NOR/INV8_base_2
add mapped point rosc_stress/rosc_control/pwr_NOR/INV8_base_3 rosc_stress_rosc_control_pwr_NOR/INV8_base_3
add mapped point rosc_stress/rosc_control/pwr_NOR/INV8_base_4 rosc_stress_rosc_control_pwr_NOR/INV8_base_4
add mapped point rosc_stress/rosc_control/pwr_inv rosc_stress_rosc_control_pwr_inv
add mapped point rosc_stress/rosc_control/pwr_inv/AND2_OFF rosc_stress_rosc_control_pwr_inv/AND2_OFF
add mapped point rosc_stress/rosc_control/pwr_inv/INV rosc_stress_rosc_control_pwr_inv/INV
add mapped point rosc_stress/rosc_control/pwr_inv/INV8_base_1 rosc_stress_rosc_control_pwr_inv/INV8_base_1
add mapped point rosc_stress/rosc_control/pwr_inv/INV8_base_2 rosc_stress_rosc_control_pwr_inv/INV8_base_2
add mapped point rosc_stress/rosc_control/pwr_inv/INV8_base_3 rosc_stress_rosc_control_pwr_inv/INV8_base_3
add mapped point rosc_stress/rosc_control/pwr_inv/INV8_base_4 rosc_stress_rosc_control_pwr_inv/INV8_base_4
